"""Ajout des colonnes description, max_tickets, price avec type DECIMAL à l'offre

Revision ID: 55648a4991ab
Revises: 32f980dbb8de
Create Date: 2024-09-02 12:37:04.283642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55648a4991ab'
down_revision = '32f980dbb8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('max_tickets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('max_tickets')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
