"""Initial migration

Revision ID: c764e9b0c535
Revises: 
Create Date: 2024-09-14 18:48:24.204455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c764e9b0c535'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('max_tickets', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth0_user_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth0_user_id')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('user_link', sa.String(), nullable=False),
    sa.Column('offer_link', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_link'], ['offer.id'], ),
    sa.ForeignKeyConstraint(['user_link'], ['user.auth0_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payement_id', sa.String(length=1000), nullable=False),
    sa.Column('user_link', sa.String(), nullable=False),
    sa.Column('offer_link', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offer_link'], ['offer.id'], ),
    sa.ForeignKeyConstraint(['user_link'], ['user.auth0_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('cart')
    op.drop_table('user')
    op.drop_table('offer')
    # ### end Alembic commands ###
